import type { TransportOrderDetail } from '../../transport-orders/types'
import type { DossierActivity, DossierDetail } from '../types'

/** Volledige DossierDetail-fixture; overrides per test. */
export function dossierDetail(overrides: Partial<DossierDetail> = {}): DossierDetail {
  return {
    id: 'd-1',
    dossierNumber: 'DOS-0001',
    title: 'Nexans NV — 12-08-2026',
    description: null,
    status: 'Open',
    customerId: 'c-1',
    customerName: 'Nexans NV',
    responsibleUserId: null,
    responsibleName: null,
    closedAt: null,
    notes: null,
    createdAt: '2026-08-12T09:00:00Z',
    orders: [],
    relations: [],
    incidents: [],
    financials: { agreedOrderTotal: 0, invoicedTotal: 0, estimatedIncidentCost: 0, actualIncidentCost: 0 },
    customerReference: 'ABC-458',
    dossierDate: '2026-08-12',
    legalEntityId: 'le-1',
    legalEntityName: 'Transp. BV',
    version: 'v-1',
    activities: [],
    readiness: [],
    ...overrides,
  }
}

export function dossierActivity(overrides: Partial<DossierActivity> = {}): DossierActivity {
  return {
    id: 'a-1',
    activityTypeId: 'at-1',
    activityTypeCode: 'DIRECT_TRANSPORT',
    activityTypeName: 'Direct transport',
    icon: 'truck',
    hasStops: true,
    supportsGoods: true,
    allowsDuration: false,
    sequence: 1,
    label: null,
    linkedTransportOrderId: null,
    linkedOrderNumber: null,
    linkedOrderStatus: null,
    linkedActivityId: null,
    plannedDate: null,
    durationHours: null,
    notes: null,
    ...overrides,
  }
}

/** Minimale maar type-volledige TransportOrderDetail voor de samenvattingssecties. */
export function orderDetail(overrides: Partial<TransportOrderDetail> = {}): TransportOrderDetail {
  return {
    id: 'o-1',
    orderNumber: 'ORD-0001',
    orderDate: '2026-08-12',
    customerId: 'c-1',
    customerName: 'Nexans NV',
    customerReference: 'ABC-458',
    status: 'Confirmed',
    goodsDescription: '2 europallets',
    quantity: null,
    quantityUnit: null,
    quantityUnitCode: null,
    weightKg: null,
    volumeM3: null,
    palletCount: null,
    adrRequired: false,
    craneRequired: false,
    agreedPrice: 428.5,
    notes: null,
    cancellationReason: null,
    stops: [
      {
        id: 's-1',
        sequence: 1,
        stopType: 'Loading',
        locationId: null,
        locationCode: null,
        locationName: 'Nexans site Antwerpen',
        address: 'Noorderlaan 10',
        postalCode: '2030',
        city: 'Antwerpen',
        countryCode: 'BE',
        plannedFrom: '2026-08-12T07:00:00Z',
        plannedTo: '2026-08-12T08:00:00Z',
        requestedFrom: null,
        requestedTo: null,
        confirmedFrom: null,
        confirmedTo: null,
        earliestAllowed: null,
        latestAllowed: null,
        appointmentRequired: false,
        appointmentReference: null,
        reference: null,
        instructions: null,
        accessInstructions: null,
        loadingInstructions: null,
        unloadingInstructions: null,
      },
    ],
    cargoItems: [
      {
        id: 'ci-1',
        sequence: 1,
        description: 'Europallet',
        barcode: null,
        expectedQuantity: 2,
        quantityUnit: 'europallet',
        quantityUnitCode: 'EUROPALLET',
        notes: null,
        unitType: null,
        unitTypeLabel: null,
        totalWeightKg: null,
        weightPerUnitKg: null,
        lengthMeters: null,
        widthMeters: null,
        heightMeters: null,
        volumeM3: null,
        volumeIsManual: false,
        adrRequired: false,
        adrDetails: null,
        stackable: true,
        reference: null,
        loadingStopId: null,
        unloadingStopId: null,
        palletCount: null,
      },
    ],
    allowedTransitions: [],
    allowedCorrections: [],
    canCancel: false,
    priority: 'Normal',
    legalEntityId: null,
    dieselSurchargeOverride: false,
    dieselSurchargePercentOverride: null,
    dieselSurchargeOverrideReason: null,
    calculatedPrice: null,
    priceIsManual: false,
    priceOverrideReason: null,
    pricingLines: null,
    serviceLines: null,
    pricingSnapshot: null,
    pricingSource: 'Contract',
    oneOffFixedAmount: null,
    oneOffIncludedLoadingMinutes: null,
    oneOffIncludedUnloadingMinutes: null,
    oneOffIncludedCombinedMinutes: null,
    oneOffExtraHourlyRate: null,
    oneOffNotes: null,
    totalWithProposed: null,
    includedLoadingMinutesOverride: null,
    includedUnloadingMinutesOverride: null,
    extraTimeHourlyRateOverride: null,
    extraTimeRoundingStepMinutes: null,
    extraTimeMinimumBillableMinutes: null,
    version: 'ov-1',
    dossierId: 'd-1',
    dossierNumber: 'DOS-0001',
    ...overrides,
  }
}
