namespace TransportationService.Api.Modules.Incidents.Dtos;

public record IncidentListItemDto(
    Guid Id,
    string Title,
    string IncidentType,
    string? CustomTypeName,
    string Status,
    string Severity,
    string? CustomerName,
    string? ResponsibleName,
    string? DossierNumber,
    DateOnly? DueDate,
    bool IsOverdue,
    DateTime CreatedAt);

public record IncidentDetailDto(
    Guid Id,
    string Title,
    string Description,
    string IncidentType,
    string? CustomTypeName,
    string Status,
    string Severity,
    string? Cause,
    Guid? ResponsibleUserId,
    string? ResponsibleName,
    string? CustomerImpact,
    string? OperationalImpact,
    string? FinancialImpact,
    decimal? EstimatedCost,
    decimal? ActualCost,
    Guid? CustomerId,
    string? CustomerName,
    Guid? DriverId,
    string? DriverName,
    Guid? VehicleId,
    string? VehicleLabel,
    Guid? TrailerId,
    string? TrailerLabel,
    Guid? TransportOrderId,
    string? TransportOrderNumber,
    Guid? TripId,
    string? TripNumber,
    Guid? DossierId,
    string? DossierNumber,
    DateOnly? DueDate,
    string? Resolution,
    DateTime? ResolvedAt,
    DateTime CreatedAt,
    IReadOnlyList<string> AllowedStatusChanges);

public record SaveIncidentRequest(
    string Title,
    string Description,
    string IncidentType,
    string Severity,
    string? CustomTypeName = null,
    string? Cause = null,
    Guid? ResponsibleUserId = null,
    string? CustomerImpact = null,
    string? OperationalImpact = null,
    string? FinancialImpact = null,
    decimal? EstimatedCost = null,
    decimal? ActualCost = null,
    Guid? CustomerId = null,
    Guid? DriverId = null,
    Guid? VehicleId = null,
    Guid? TrailerId = null,
    Guid? TransportOrderId = null,
    Guid? TripId = null,
    Guid? DossierId = null,
    DateOnly? DueDate = null);

public record ChangeIncidentStatusRequest(string Status, string? Resolution = null);
